List<Map<String, String>> productFood = [
  {
    'title': 'Zinger Burger',
    'image': 'assets/images/zingerBurger.png',
    'price': '33',
    'type': 'Burger',
    'location': 'Cairo',
    'food': 'Burger',
  },
  {
    'title': 'Roll Paratha',
    'image': 'assets/images/rollBurger.png',
    'price': '30',
    'type': 'Burger',
    'location': 'Alex',
    'food': 'Burger',
  },
  {
    'title': 'Long burger',
    'image': 'assets/images/longBurger.png',
    'price': '41',
    'type': 'Burger',
    'location': 'Riyadh',
    'food': 'Burger',
  },
  {
    'title': 'Sandwich',
    'image': 'assets/images/sandwich.png',
    'price': '22',
    'type': 'Burger',
    'location': 'Dubai',
    'food': 'Burger',
  },
  {
    'title': 'Pizza roll',
    'image': 'assets/images/pizzaRoll.png',
    'price': '24',
    'type': 'Burger',
    'location': 'Cairo',
    'food': 'Burger',
  },
  {
    'title': 'Tomatto Soup',
    'image': 'assets/images/tomatoSoup.png',
    'price': '14',
    'type': 'Soup',
    'location': 'Alex',
    'food': 'Soup',
  },
  {
    'title': 'Carrot soup',
    'image': 'assets/images/carrotSoup.png',
    'price': '11',
    'type': 'Soup',
    'location': 'Riyadh',
    'food': 'Soup',
  },
  {
    'title': 'Misso Soup',
    'image': 'assets/images/missoSoup.png',
    'price': '15',
    'type': 'Soup',
    'location': 'Dubai',
    'food': 'Soup',
  },
  {
    'title': 'Mushroom soup',
    'image': 'assets/images/mushroomSoup.png',
    'price': '12',
    'type': 'Soup',
    'location': 'Cairo',
    'food': 'Soup',
  },
  {
    'title': 'Macaron',
    'image': 'assets/images/Macaron.png',
    'price': '4',
    'type': 'Dessert',
    'location': 'Alex',
    'food': 'Dessert',
  },
  {
    'title': 'Cupcake',
    'image': 'assets/images/cupcake.png',
    'price': '6',
    'type': 'Dessert',
    'location': 'Riyadh',
    'food': 'Dessert',
  },
  {
    'title': 'Biscuts',
    'image': 'assets/images/biscuts.png',
    'price': '8',
    'type': 'Dessert',
    'location': 'Riyadh',
    'food': 'Dessert',
  },
];
